import {Asset} from './asset';


export const ASSETS: Asset[] =  
  [ { AssetID: 868581,
      AssetName: 'cfbxcvbcdd',
      AssetType: 'Term Loan',
      AssetAbbrev: 'cfbxcvbc' },
    { AssetID: 868580,
      AssetName: 'xdfghdgfsh',
      AssetType: 'Term Loan',
      AssetAbbrev: 'xdfghdgfsh' },
    { AssetID: 868569,
      AssetName: 'GOVENRMENT FUND',
      AssetType: 'Private Fund',
      AssetAbbrev: 'FUND123456' },
    { AssetID: 868568,
      AssetName: 'BTCEUR 20190819',
      AssetType: 'Forward',
      AssetAbbrev: 'BTCEUR 20190819' },
    { AssetID: 868567,
      AssetName: 'XCDGBP 20190819',
      AssetType: 'Forward',
      AssetAbbrev: 'XCDGBP 20190819' },
    { AssetID: 868566,
      AssetName: 'DUNDER MIFFLIN',
      AssetType: 'Bond',
      AssetAbbrev: 'DDMF 5.375% 2028' },
    { AssetID: 868565,
      AssetName: 'CANT TOUCH THIS 5.75% 08/1',
      AssetType: 'Bond',
      AssetAbbrev: 'CTT 5.75% 2027' },
    { AssetID: 868564,
      AssetName: 'POKEMON 2019-1A C 144A  ',
      AssetType: 'CLO Debt',
      AssetAbbrev: 'POKE 2019-1A C 144A  ' },
    { AssetID: 868563,
      AssetName: 'IN YOUR FACE UNITS',
      AssetType: 'Convertible Bond',
      AssetAbbrev: 'IYF UNITS' },
    { AssetID: 868562,
      AssetName: 'MISTER FROG',
      AssetType: 'Bond',
      AssetAbbrev: 'MISTER FROG' } ];